export const OUTCOMES = ['Efficiency','Accuracy','Access','Security'];
export const OUTCOME_COLORS = { Efficiency:'#3f51b5', Accuracy:'#2e7d32', Access:'#F76B15', Security:'#CA244D' };
export const OUTCOME_ICONS = { Efficiency:'bolt', Accuracy:'target', Access:'lock_open', Security:'security' };
export const RESPONSIBILITIES = [
  { id:'case-filing', name:'Case Filing', icon:'folder_open_alt', description:'Submitting, reviewing, and accepting case filings.', goals:{ Efficiency:'Decrease filer wait times by minimizing manual review and accelerating processing', Accuracy:'Decrease submission revisions by accurately transferring information to the CMS, ensuring compliance', Access:'Decrease barriers for self-represented litigants with access to electronic filing options', Security:'Decrease errors in filings and ensure compliance with document handling to protect court integrity' }},
  { id:'correspondence', name:'Court Correspondence', icon:'email_arrow_right', description:'Sending timely, accurate court correspondence to parties and stakeholders.', goals:{ Efficiency:'Decrease operational costs by streamlining correspondence processes', Accuracy:'Decrease human error by automating correspondence processes', Access:'Increase compliance by providing relevant information in a timely manner', Security:'Decrease error by limiting access to court correspondence' }},
  { id:'hearings', name:'Courtroom Operations', icon:'gavel_alt', description:'Managing hearings end-to-end with accurate schedules and secure access.', goals:{ Efficiency:'Decrease administrative workload through automation', Accuracy:'Increase judicial integrity by keeping case information accurate and up to date', Access:'Increase timely, role-appropriate access to case information through secure, digital channels', Security:'Increase protection of sensitive information and decrease unauthorized data access by enforcing security controls' }},
  { id:'data-integration', name:'Data Integration', icon:'database_sync', description:'Sharing and integrating data across systems for accuracy and visibility.', goals:{ Efficiency:'Increase operational efficiencies with integrated systems', Accuracy:'Decrease user error and support data-driven planning with integrated systems', Access:'Increase transparency and access to justice by using integrated systems', Security:'Increase situational awareness by securing robust data visibility' }},
  { id:'payments', name:'Payment Processing', icon:'payments', description:'Collecting and processing payments with self-service and PCI-aligned controls.', goals:{ Efficiency:'Decrease manual payment collection through self-service', Accuracy:'Decrease steps and staffing needs in the payment process', Access:'Increase operational efficiencies by expanding digital payment capabilities', Security:'Increase security by strengthening PCI-compliant payment processing protocols' }},
  { id:'data-insights', name:'Data Focused Management', icon:'google_analytics', description:'Using analytics and reporting to manage people, processes, and performance.', goals:{ Efficiency:'Decrease process bottlenecks using automated data collection and visualization', Accuracy:'Increase data-driven decision-making for process and personnel management', Access:'Increase operational transparency for judges and court administrators with clear, data-driven insights', Security:'Increase protection of sensitive information, ensuring operational metrics are accessible only to authorized decision-makers' }},
  { id:'records', name:'Court Records', icon:'file_document_multiple', description:'Maintaining secure, accurate court records and continuity of operations.', goals:{ Efficiency:'Increase efficiencies by leveraging cloud-based systems', Accuracy:'Increase accuracy in records management with a modern system', Access:'Decrease Return to Operations times by planning for disaster recovery', Security:'Increase security and redundancy with robust protocols' }},
  { id:'jury', name:'Jury Management', icon:'account_group', description:'Summoning, communicating with, and supporting jurors through the jury process.', goals:{ Efficiency:'Increase efficiency in jury management processes with automated communications', Accuracy:'Increase accuracy of juror information with questionnaire completion', Access:'Increase juror convenience and decrease manual intervention by automating notifications', Security:'Increase security of juror data with authentication controls' }},
  { id:'orders', name:'Order Processing', icon:'stamper', description:'Processing, signing, and recording orders with minimal delay and proper access.', goals:{ Efficiency:'Decrease order processing delays with streamlined signing and recording of orders', Accuracy:'Increase accuracy of orders with error-free orders for judge review', Access:'Increase access and editing capabilities of orders to judicial officers and court personnel', Security:'Increase security of orders by limiting visibility to staff evaluating and processing' }},
];
export const MEASURES = {
  'case-filing':[{name:'Use of rejection codes by each staff member',outcome:'Accuracy',source:'eFile Analytics'},{name:'Rejection rate per staff member compared to average',outcome:'Accuracy',source:'eFile Analytics'},{name:'Avg time between submission and envelope opened',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Avg processing duration (submission to acceptance/rejection)',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Avg time spent on filing reviews per staff member',outcome:'Efficiency',source:'eFile Analytics'},{name:'Frequency of data field updates after initial submission',outcome:'Accuracy',source:'Enterprise Justice'},{name:'Self-represented litigants able to file electronically',outcome:'Access',source:'Guide & File'},{name:'Security error rate for filed documents',outcome:'Security',source:'Enterprise Justice'},{name:'Redaction error rate for filed documents',outcome:'Security',source:'Enterprise Justice'}],
  'correspondence':[{name:'Failure to Appear (FTA) rate relative to scheduled hearings',outcome:'Access',source:'Court Analytics'},{name:'Employee hours per unit of correspondence',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Avg individuals with access to correspondence prior to addressee',outcome:'Accuracy',source:'Enterprise Justice'},{name:'Percentage of FTAs relative to caseload',outcome:'Access',source:'Court Analytics'},{name:'Percentage of FTPs relative to caseload',outcome:'Access',source:'Court Analytics'},{name:'Percentage of juror no-shows relative to caseload',outcome:'Access',source:'Court Analytics'},{name:'Percentage of default judgments relative to caseload',outcome:'Access',source:'Court Analytics'},{name:'Percentage of hearing resets relative to caseload',outcome:'Access',source:'Court Analytics'}],
  'hearings':[{name:'Number of settings delayed or rescheduled',outcome:'Efficiency',source:'Court Analytics'},{name:'Clearance Rate',outcome:'Efficiency',source:'Court Analytics'},{name:'Age of Active Cases',outcome:'Efficiency',source:'Court Analytics'},{name:'Time to disposition',outcome:'Efficiency',source:'Court Analytics'},{name:'Hearing resets relative to caseload',outcome:'Efficiency',source:'Court Analytics'},{name:'Employee hours checking in participants',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Hearings delayed due to admin conflicts',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Errors in hearing documentation or schedules',outcome:'Accuracy',source:'Enterprise Justice'},{name:'Case/hearing/scheduling info available online',outcome:'Access',source:'re:Search'},{name:'Calendar updates synchronized across systems',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Hearings conducted virtually',outcome:'Access',source:'Enterprise Justice'},{name:'Unauthorized access to hearing or case data',outcome:'Security',source:'Enterprise Justice'},{name:'Consistency of role-based access controls',outcome:'Security',source:'Enterprise Justice'},{name:'Hearing-related tasks completed during hearing',outcome:'Efficiency',source:'Courtroom Tools'}],
  'data-integration':[{name:'Number of active two-way integration points',outcome:'Efficiency',source:'CIP 2.0'},{name:'Data exchange latency between systems',outcome:'Accuracy',source:'Enterprise Justice'}],
  'payments':[{name:'Failure to Pay (FTP) rate',outcome:'Access',source:'Court Analytics'},{name:'Over-the-counter vs electronic transactions',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Payments made at courthouse window',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Transactions requiring double entry',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Transactions requiring single staff entry',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Transactions requiring no staff entry',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Staff involved per payment transaction',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Traffic cases requiring in-person visits',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Accessibility compliance of payment system',outcome:'Security',source:'Defendant Access'},{name:'PCI compliance level',outcome:'Security',source:'Payment Processing'}],
  'data-insights':[{name:'Frequency of data feed updates',outcome:'Efficiency',source:'All Analytics'},{name:'Supervisor access to operational data',outcome:'Accuracy',source:'Court Analytics'},{name:'Hours to compile operational reports monthly',outcome:'Efficiency',source:'All Analytics'},{name:'Staff activities management can track',outcome:'Accuracy',source:'Court Analytics'},{name:'Processes that can be A/B tested',outcome:'Accuracy',source:'Enterprise Data Platform'},{name:'Key processes graphically represented',outcome:'Access',source:'Court Analytics'},{name:'Non-decision-makers with access to operational data',outcome:'Security',source:'Court Analytics'}],
  'records':[{name:'Employee hours maintaining redundant paper files',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Adherence to retention standards',outcome:'Accuracy',source:'Enterprise Justice'},{name:'Written disaster recovery procedures',outcome:'Access',source:'AWS GovCloud'},{name:'Frequency of disaster recovery rehearsals',outcome:'Security',source:'AWS GovCloud'},{name:'Degree of infrastructure redundancy',outcome:'Efficiency',source:'AWS GovCloud'},{name:'Frequency of CMS software updates',outcome:'Security',source:'Tyler Technologies'},{name:'Case information exposed to unauthorized individuals',outcome:'Security',source:'Enterprise Justice'},{name:'Number of public records requests received',outcome:'Efficiency',source:'re:Search'},{name:'Frequency of IP address blocking events',outcome:'Security',source:'re:Search'},{name:'Percentage of case/document types available online',outcome:'Access',source:'re:Search'}],
  'jury':[{name:'Juror No-Show rate relative to summons issued',outcome:'Efficiency',source:'Jury Analytics'},{name:'Jury Yield Rate',outcome:'Efficiency',source:'Jury Analytics'},{name:'Jury Utilization Rate',outcome:'Efficiency',source:'Jury Analytics'},{name:'Juror check-in wait time',outcome:'Efficiency',source:'Enterprise Jury Manager'},{name:'Jurors empaneled without entering courthouse',outcome:'Efficiency',source:'Enterprise Jury Manager'},{name:'Incorrect contact data elements',outcome:'Accuracy',source:'Enterprise Jury Manager'},{name:'Automated jury communications frequency',outcome:'Efficiency',source:'Tyler Messaging'},{name:'Clarification calls relative to summons',outcome:'Efficiency',source:'Enterprise Jury Manager'},{name:'Human intervention per communication channel',outcome:'Efficiency',source:'Enterprise Jury Manager'},{name:'SOC compliance level of jury system',outcome:'Security',source:'Enterprise Jury Manager'},{name:'Authentication controls protecting juror data',outcome:'Security',source:'Enterprise Jury Manager'}],
  'orders':[{name:'Orders requiring administrative correction',outcome:'Accuracy',source:'Enterprise Justice'},{name:'Time between hearing conclusion and order availability',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Time between signing and order in case record',outcome:'Efficiency',source:'Enterprise Justice'},{name:'Staff members updating records per hearing',outcome:'Security',source:'Enterprise Justice'}],
};
export const STEPS = {
  'case-filing':{full:'Filing – Provide a streamlined, accurate, and secure process for submitting, reviewing, and accepting case filings',actions:['Move filing online for high-volume case types with File & Serve and Guide & File','Standardize and document filing processing','Track filing performance across staff with eFile Analytics','Auto-accept trusted formulaic filings from partners','Automate high-volume filing with Document Automation']},
  'correspondence':{full:'Court Correspondence – Send Timely, Quality Information',actions:['Electronically serve parties with E-Notifications and Notification Sets','Send hearing reminders via text with Enterprise Justice Text Messaging','Send jury summons and reminders with Enterprise Jury Manager','Send automated payment reminders with Defendant Access']},
  'hearings':{full:'Conduct Hearings – Manage and execute hearings end-to-end',actions:['Enable digital case file review with Courtroom Tools (Judge)','Process minutes and generate orders in real time with Clerk Edition','Register hearing attendees with Courtroom Check-In','Publish court calendar data with Session Sync']},
  'data-integration':{full:'Data Sharing & Integrations – Establish an integrated and accessible data environment',actions:['Implement Configurable Integration Publishing 2.0','Consult an Alliance Program Manager for integration strategy','Execute personalized Alliance Strategy','Implement Cloud Gavel for warrant review']},
  'payments':{full:'Process Payment Transactions – Provide Remote, Integrated Payment Options',actions:['Accept filing payments online with File & Serve','Provide online/phone payment options with Defendant Access','Charge for document access with re:Search','Set up payment plans with Auto Close in Enterprise Justice','Process PCI-compliant payments with Ingenico terminals','Streamline disbursements with Managed Disbursements']},
  'data-insights':{full:'Data-Driven Management – Manage People and Processes Using Data-Rich Analysis',actions:['Track intake clerk productivity with eFile Analytics','Monitor court/clerk productivity with Court Analytics','Track tailored data with Enterprise Data Platform','Analyze jury data with Jury Analytics']},
  'records':{full:'Maintain Court Records – Maintain records securely for continuity and protection',actions:['Auto-redact sensitive data with Auto Redaction','Import attorney records with State Bar Interface','Host in AWS GovCloud secure environment','Stay current on Tyler software stack with proactive deployment']},
  'jury':{full:'Jury Process Management – Provide a streamlined, citizen-serving Jury process',actions:['Manage jury pools with Enterprise Jury Manager','Deliver jury compensation with Tyler Disbursements','Automate summons with Summons Direct','Provide self-service confirmation with Jury Voice','Enable juror self-service portal with Juror Access Online','Automate jury communications with Tyler Messaging']},
  'orders':{full:'Back Office Processing – Streamline order and case processing',actions:['Enable eSignatures for judges, clerks, attorneys','Automate workflows with Task Manager and Task Queues','Streamline appeal records with Record on Appeal','Collaborative form management with Staff Reports','Track deadlines with Time Standards','Automate case processing with Case Plans','Automate repetitive processes with Process Builder']},
};
export const MATURITY_LEVELS = [
  {level:1,label:'Initial',color:'#b00020',desc:'Ad-hoc, manual processes with no standardization'},
  {level:2,label:'Developing',color:'#d14900',desc:'Some digitization, basic processes documented'},
  {level:3,label:'Defined',color:'#3f51b5',desc:'Standardized processes, core systems deployed'},
  {level:4,label:'Managed',color:'#2e7d32',desc:'Data-driven optimization, integrated systems'},
  {level:5,label:'Optimized',color:'#00695c',desc:'Fully automated, continuously improving'},
];

/** Given flat scores { [respId-outcome]: number }, return { respScores, overall } for display. */
export function getAssessmentSummary(scores) {
  if (!scores || typeof scores !== 'object') return { respScores: [], overall: 0 };
  const respScores = RESPONSIBILITIES.map(r => {
    const byOutcome = Object.fromEntries(OUTCOMES.map(o => [o, scores[`${r.id}-${o}`] || 0]));
    const vals = OUTCOMES.map(o => byOutcome[o]).filter(Boolean);
    const avg = vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : 0;
    return { ...r, avg, byOutcome, ratedCount: vals.length };
  });
  const ratedRespScores = respScores.filter(r => r.ratedCount > 0);
  const overall = ratedRespScores.length
    ? parseFloat((ratedRespScores.reduce((s, r) => s + r.avg, 0) / ratedRespScores.length).toFixed(1))
    : 0;
  return { respScores, overall };
}
